services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: norsklaer_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DATABASE_HOST=db
      - DATABASE_NAME=norsklaer_dev
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py load_sample_data &&
             python manage.py runserver 0.0.0.0:8000"

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_BASE_URL=http://backend:8000/api/v1
    depends_on:
      - backend

volumes:
  postgres_data: